package com.project.domain;

import static com.project.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class CsytOneBssAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCsytOneBssAllPropertiesEquals(CsytOneBss expected, CsytOneBss actual) {
        assertCsytOneBssAutoGeneratedPropertiesEquals(expected, actual);
        assertCsytOneBssAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCsytOneBssAllUpdatablePropertiesEquals(CsytOneBss expected, CsytOneBss actual) {
        assertCsytOneBssUpdatableFieldsEquals(expected, actual);
        assertCsytOneBssUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCsytOneBssAutoGeneratedPropertiesEquals(CsytOneBss expected, CsytOneBss actual) {
        assertThat(expected)
            .as("Verify CsytOneBss auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCsytOneBssUpdatableFieldsEquals(CsytOneBss expected, CsytOneBss actual) {
        assertThat(expected)
            .as("Verify CsytOneBss relevant properties")
            .satisfies(e -> assertThat(e.getMaCsyt()).as("check maCsyt").isEqualTo(actual.getMaCsyt()))
            .satisfies(e -> assertThat(e.getMaThuebao()).as("check maThuebao").isEqualTo(actual.getMaThuebao()))
            .satisfies(e -> assertThat(e.getMaDuan()).as("check maDuan").isEqualTo(actual.getMaDuan()))
            .satisfies(e -> assertThat(e.getTrangthai()).as("check trangthai").isEqualTo(actual.getTrangthai()))
            .satisfies(e -> assertThat(e.getThoigianCapnhat()).as("check thoigianCapnhat").isEqualTo(actual.getThoigianCapnhat()))
            .satisfies(e -> assertThat(e.getMaTinh()).as("check maTinh").isEqualTo(actual.getMaTinh()))
            .satisfies(e -> assertThat(e.getMaSpdv()).as("check maSpdv").isEqualTo(actual.getMaSpdv()))
            .satisfies(e -> assertThat(e.getMaHopdong()).as("check maHopdong").isEqualTo(actual.getMaHopdong()))
            .satisfies(e -> assertThat(e.getNgaykyHopdong()).as("check ngaykyHopdong").isEqualTo(actual.getNgaykyHopdong()))
            .satisfies(e -> assertThat(e.getHieulucTu()).as("check hieulucTu").isEqualTo(actual.getHieulucTu()))
            .satisfies(e -> assertThat(e.getHieulucDen()).as("check hieulucDen").isEqualTo(actual.getHieulucDen()))
            .satisfies(e -> assertThat(e.getTenKhachhang()).as("check tenKhachhang").isEqualTo(actual.getTenKhachhang()))
            .satisfies(e -> assertThat(e.getDiachiKhachhang()).as("check diachiKhachhang").isEqualTo(actual.getDiachiKhachhang()))
            .satisfies(e -> assertThat(e.getMota()).as("check mota").isEqualTo(actual.getMota()))
            .satisfies(e -> assertThat(e.getLastUser()).as("check lastUser").isEqualTo(actual.getLastUser()))
            .satisfies(
                e ->
                    assertThat(e.getLastModified())
                        .as("check lastModified")
                        .usingComparator(zonedDataTimeSameInstant)
                        .isEqualTo(actual.getLastModified())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCsytOneBssUpdatableRelationshipsEquals(CsytOneBss expected, CsytOneBss actual) {}
}
